In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 


In [2]:
data=pd.read_csv("wearable_sports_health_dataset.csv")
data

,Record_ID,Athlete_ID,Timestamp,Heart_Rate,Body_Temperature,Blood_Pressure,Blood_Oxygen,Step_Count,Activity_Status,Latitude,Longitude,Secure_Transmission_Status
0,1,ATH002,2025-04-10 09:00:00,63,37.1,133/78,96,528,Walking,12.927365,80.116767,0
1,2,ATH009,2025-04-10 09:05:00,71,37.0,128/83,95,330,Running,12.922186,80.115054,0
2,3,ATH001,2025-04-10 09:10:00,131,37.2,116/90,100,858,Resting,12.922204,80.115893,0
3,4,ATH001,2025-04-10 09:15:00,157,37.5,135/75,100,732,Cycling,12.922779,80.112153,0
4,5,ATH006,2025-04-10 09:20:00,73,36.9,112/82,95,667,Cycling,12.926037,80.118071,0
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,ATH007,2025-04-12 02:15:00,79,37.2,136/87,99,355,Running,12.926434,80.111569,1
496,497,ATH008,2025-04-12 02:20:00,169,36.7,125/75,95,803,Cycling,12.922409,80.119701,0
497,498,ATH001,2025-04-12 02:25:00,124,36.9,117/87,100,687,Resting,12.928171,80.110788,0
498,499,ATH008,2025-04-12 02:30:00,162,36.7,128/84,95,810,Resting,12.923161,80.119807,0


In [3]:
print(data.isnull().sum())

Record_ID                     0
Athlete_ID                    0
Timestamp                     0
Heart_Rate                    0
Body_Temperature              0
Blood_Pressure                0
Blood_Oxygen                  0
Step_Count                    0
Activity_Status               0
Latitude                      0
Longitude                     0
Secure_Transmission_Status    0
dtype: int64


In [10]:
data=data.drop([
    "Record_ID",                    
    "Athlete_ID",                    
    "Timestamp" ,
    "Latitude",                      
    "Longitude",                     
    "Secure_Transmission_Status"
],axis=1)

In [11]:
print(data.isnull().sum())

Heart_Rate          0
Body_Temperature    0
Blood_Pressure      0
Blood_Oxygen        0
Step_Count          0
Activity_Status     0
dtype: int64


In [31]:
df= data.drop(columns=[
    "Record_ID",                    
    "Athlete_ID",                    
    "Timestamp" ,
    "Latitude",                      
    "Longitude",                     
    "Secure_Transmission_Status"
])
    

In [62]:
print (data.columns)

Index(['Record_ID', 'Athlete_ID', 'Timestamp', 'Heart_Rate',
       'Body_Temperature', 'Blood_Oxygen', 'Step_Count', 'Activity_Status',
       'Latitude', 'Longitude', 'Secure_Transmission_Status', 'Systolic_BP',
       'Diastolic_BP'],
      dtype='object')


In [54]:
#converting systolic and diastolic number into values 
data['Systolic_BP']=data['Systolic_BP'].astype(float)
data['Diastolic_BP']=data['Diastolic_BP'].astype(float)

In [55]:
data=data.drop(columns=['Blood_Pressure'])

In [69]:
data['Diastolic_BP']

0      78.0
1      83.0
2      90.0
3      75.0
4      82.0
       ... 
495    87.0
496    75.0
497    87.0
498    84.0
499    83.0
Name: Diastolic_BP, Length: 500, dtype: float64

In [71]:
data['Systolic_BP']

0      133.0
1      128.0
2      116.0
3      135.0
4      112.0
       ...  
495    136.0
496    125.0
497    117.0
498    128.0
499    122.0
Name: Systolic_BP, Length: 500, dtype: float64

In [73]:
#features for the model
X=df[[
    "Heart_Rate",
    "Body_Temperature",
    "Blood_Oxygen",
    "Step_Count",
    "Blood_Pressure"
]]

In [34]:
#target variable 
y=df["Activity_Status"]


In [36]:
#if Activity_status contains words like 
#Resting 
#Walking 
#Running 
#cycling  

In [81]:
#converting them into numbers 
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder()
y=le.fit_transform(y)
model.fit(X_train,y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [77]:
#training the model 
import pandas as pd
from sklearn.model_selection import train_test_split #libaries used 
from sklearn.datasets import load_iris
#load the iris dataset 
iris=load_iris()
X,y=iris.data,iris.target
#split data into temporary and testing sets 
#the temporary set includes both trainig and validation data 
X_temp,X_test,y_temp,y_test= train_test_split(X,y,test_size=0.2)
X_train,X_val,y_train,y_val=train_test_split(X_temp,y_temp,
                                              test_size=0.2)

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier

In [14]:
iris = load_iris()
X, y = iris.data, iris.target

In [15]:
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.2)

X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.2)

In [16]:
model.fit(X_train, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [17]:
import numpy as np

y_pred = model.predict(X_test)
np.unique(y_test)

array([0, 1, 2])

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

# create model
model = DecisionTreeClassifier()

# train model
model.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [24]:
model.fit(X_train,y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [25]:
#save the trained model
joblib.dump(model,"fatigue_model.pkl")

['fatigue_model.pkl']

In [13]:
STRESS_HR=100
Blood_Pressure =120/80
STRESS_OXY=95
FATIGUE_HR=90
FATIGUE_STEPS=2000
FATIGUE_TEMP=37.5

In [87]:
import numpy as np
y_pred=model.predict(X_test)
np.unique(y_test)

array([0, 1, 2])

In [91]:
activity_map={0:"Resting",1:"Walking",2:"Running"}
#converting y_pred to labels
y_pred_labels=[activity_map[i]for i in y_pred]
#converting y_test into labels
y_test_labels=[activity_map[i]for i in y_test]

In [92]:
#check model performance 
from sklearn.metrics import classification_report,confusion_matrix 
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred))

Confusion Matrix:
[[ 6  0  0]
 [ 0 11  1]
 [ 0  1 11]]


In [93]:
#to test the accuracy 
from sklearn.metrics import classification_report, accuracy_score

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Detailed metrics
print(classification_report(y_test, y_pred, target_names=['Resting','Walking','Running']))

Accuracy: 0.9333333333333333
              precision    recall  f1-score   support

     Resting       1.00      1.00      1.00         6
     Walking       0.92      0.92      0.92        12
     Running       0.92      0.92      0.92        12

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.93      0.93      0.93        30



In [101]:
# Example: new athlete reading
sample_reading = [[5, 5, 5,5]]  # HR, Temp, Blood Oxygen, Steps
predicted_status = model.predict(sample_reading)
activity_map = {0: "Resting", 1: "Walking", 2: "Running"}
print("Predicted Activity Status:", activity_map[predicted_status[0]])

Predicted Activity Status: Running
